// ---------------------------------------------------------------------------
// The upload topology, as data only. Nothing here knows about pixels — ELK
// computes every coordinate at runtime from the parent/child + edge structure.
// ---------------------------------------------------------------------------

export const ROLE = {
  client: { label: "Client", color: "#7C93B8" },
  net: { label: "Edge / transport", color: "#4C8DFF" },
  idn: { label: "Identity", color: "#A78BFA" },
  app: { label: "Application", color: "#34D399" },
  safe: { label: "Content safety", color: "#F5A524" },
  store: { label: "Storage & keys", color: "#22D3EE" },
  audit: { label: "Audit", color: "#C08457" },
};

export const THREAT = "#F2685C";

// Trust boundaries — ELK lays these out as compound (parent) nodes and sizes
// them around whatever they contain.
export const ZONES = [
  { id: "z-public", label: "Public internet", color: ROLE.client.color },
  { id: "z-edge", label: "Google edge", color: ROLE.net.color },
  { id: "z-prod", label: "Google production network", color: ROLE.app.color },
  { id: "z-store", label: "Storage plane", color: ROLE.store.color },
];

export const COMPONENTS = [
  {
    id: "client",
    zone: "z-public",
    role: "client",
    icon: "laptop",
    name: "Browser / Drive client",
    sub: "your device",
    what: "Reads the file locally and opens the connection. Everything before this point is the browser's security model, not Google's — the origin sandbox and Content Security Policy decide what code is even allowed to touch your file.",
    principles: ["Same-origin policy", "Content Security Policy"],
    threat: "Hostile script on the page",
    threatDetail:
      "A cross-site script could read the file or redirect the upload before it ever leaves. The origin model keeps foreign code out of the page holding your data.",
    fail: "If CSP blocks the script or the origin can't be verified, nothing is ever sent.",
    chipThreat: "XSS / hostile page",
  },
  {
    id: "dns",
    zone: "z-edge",
    role: "net",
    icon: "globe",
    name: "DNS + Anycast",
    sub: "resolve & route",
    what: "Resolves the Drive hostname and hands back an anycast address, routing you to the nearest of Google's edge locations rather than a single origin server.",
    principles: ["Availability", "Geographic distribution"],
    threat: "DNS spoofing",
    threatDetail:
      "A forged DNS answer would point you at an attacker's server. This is exactly why the next step authenticates the server by certificate rather than trusting the address it was given.",
    fail: "A wrong or hijacked answer is caught at the TLS step, when the certificate fails to match.",
  },
  {
    id: "gfe",
    zone: "z-edge",
    role: "net",
    icon: "shield",
    name: "Google Front End",
    sub: "TLS termination · DoS",
    what: "The GFE terminates TLS with a validated certificate and perfect forward secrecy, and absorbs volumetric attacks at the edge. This is the outer wall: the public internet ends here.",
    principles: ["Encryption in transit", "Forward secrecy", "Rate limiting", "Fail secure"],
    threat: "MITM and DDoS",
    threatDetail:
      "Authenticated TLS defeats anyone reading or altering the file in flight; a global anycast edge means a flood never concentrates on one origin.",
    fail: "Certificate mismatch or a downgrade attempt ends the connection. Abusive traffic is throttled or dropped here and never reaches Drive.",
    chipThreat: "MITM · DDoS",
    reject: "dropped — abuse",
  },
  {
    id: "api",
    zone: "z-prod",
    role: "app",
    icon: "api",
    name: "Drive API frontend",
    sub: "request routing",
    what: "Receives the forwarded request inside Google's network and orchestrates it. It trusts nothing about the request just because it arrived internally — it goes and asks Identity.",
    principles: ["Zero trust", "Separation of duties"],
    threat: "Implicit network trust",
    threatDetail:
      "The classic failure is treating 'inside the perimeter' as 'authenticated'. Every internal call here is mutually authenticated over ALTS and independently authorized.",
    fail: "An unroutable or malformed request is rejected before any file handling begins.",
  },
  {
    id: "identity",
    zone: "z-prod",
    role: "idn",
    icon: "id",
    name: "Identity & OAuth",
    sub: "authn + scopes",
    what: "Verifies the account session or OAuth access token on this specific request, and returns the caller's identity along with the scopes it was actually granted.",
    principles: ["Zero trust", "Authentication", "Least privilege", "Fail secure"],
    threat: "Stolen token or replayed session",
    threatDetail:
      "A leaked bearer token impersonates you completely, so lifetimes are short and tokens are bound; narrow scopes like drive.file confine an app to only the files it created.",
    fail: "Missing, expired, or invalid credential → 401, and the upload stops before a byte is stored.",
    chipThreat: "stolen token",
    reject: "401 unauthenticated",
  },
  {
    id: "upload",
    zone: "z-prod",
    role: "app",
    icon: "upload",
    name: "Upload service",
    sub: "resumable · validate · quota",
    what: "Issues an unguessable, short-lived session URI and accepts the file in chunks, checking size, type, checksum, and storage quota as they arrive. It is the fan-out point for everything downstream.",
    principles: ["Input validation", "Integrity", "Resource limits", "Capability binding"],
    threat: "Malformed input and session URI leakage",
    threatDetail:
      "Oversized or malformed uploads are used to exhaust storage or crash downstream parsers; a leaked upload URI would let someone write into your session, so it is bound to the identity that opened it.",
    fail: "403 on quota or insufficient scope; a checksum mismatch re-requests the chunk; an expired session URI returns 410.",
    chipThreat: "malformed input",
    reject: "403 scope / quota",
  },
  {
    id: "scanner",
    zone: "z-prod",
    role: "safe",
    icon: "scan",
    name: "Malware scanning",
    sub: "content inspection",
    what: "Scans the content against Google's malware signals before the file can be shared or downloaded, including for files shared inside an organization.",
    principles: ["Defense in depth", "Containment", "Assume breach"],
    threat: "Drive as a delivery channel",
    threatDetail:
      "Attackers upload a payload and share the link, borrowing the trust in a google.com domain to slip past filters that would block an unknown host.",
    fail: "Detected malware is blocked from sharing and download, and flagged to the owner and admins.",
    chipThreat: "malware upload",
    reject: "blocked — malware",
  },
  {
    id: "dlp",
    zone: "z-prod",
    role: "safe",
    icon: "tag",
    name: "DLP engine",
    sub: "classify · label · enforce",
    enterprise: true,
    what: "For Workspace organizations, inspects content against policy — card numbers, credentials, regulated data — and applies labels that govern how the file may be shared.",
    principles: ["Data governance", "Least privilege", "Auditability"],
    threat: "Exfiltration and accidental exposure",
    threatDetail:
      "Sensitive data leaving through a personal account or a public link, far more often carelessness than malice — which is why it is enforced by policy rather than trust.",
    fail: "A violation can block the upload, strip sharing, or quarantine the file, and raises an admin alert.",
    chipThreat: "data exfiltration",
    reject: "quarantined — policy",
  },
  {
    id: "audit",
    zone: "z-prod",
    role: "audit",
    icon: "log",
    name: "Audit log",
    sub: "who did what, when",
    what: "Records the access and admin activity behind the upload, so the entire path above can be reconstructed after the fact.",
    principles: ["Auditability", "Non-repudiation", "Detect and respond"],
    threat: "Undetected compromise",
    threatDetail:
      "Prevention eventually fails. Logging is what turns a silent breach into a detectable, reconstructable event — the assumption is not if, but when.",
    fail: "Logging is write-path independent: it records the refusal too, so blocked attempts are as visible as successful ones.",
  },
  {
    id: "chunk",
    zone: "z-store",
    role: "store",
    icon: "chunk",
    name: "Chunk + encrypt",
    sub: "per-chunk DEK · AES-256",
    what: "Splits the file into chunks and encrypts each one under its own data encryption key, then spreads them across the storage fleet. No single key opens the whole file.",
    principles: ["Encryption at rest", "Blast-radius reduction", "Isolation"],
    threat: "Bulk data compromise",
    threatDetail:
      "Because each chunk carries a different key and the chunks are scattered, reaching the storage layer yields fragments rather than files.",
    fail: "If a key cannot be generated or a chunk fails its integrity check, that chunk is never committed.",
  },
  {
    id: "keystore",
    zone: "z-store",
    role: "store",
    icon: "key",
    name: "Keystore (KEK)",
    sub: "key hierarchy",
    what: "Holds the key encryption keys centrally. Each data key is wrapped by a KEK and stored beside its chunk, so data and the authority to read it are deliberately kept apart.",
    principles: ["Key hierarchy", "Separation of duties", "Fail closed", "Auditability"],
    threat: "Key compromise and insider access",
    threatDetail:
      "Holding keys apart from data means access to storage is not access to content — every unwrap is a separate authorization decision that is checked and recorded.",
    fail: "If Keystore denies the unwrap, the service simply cannot read the data. Access fails closed rather than open.",
    chipThreat: "insider access",
    reject: "fail closed",
  },
  {
    id: "colossus",
    zone: "z-store",
    role: "store",
    icon: "disk",
    name: "Colossus",
    sub: "durable chunk storage",
    what: "Google's distributed file system stores the encrypted chunks with redundancy across machines and failure domains.",
    principles: ["Durability", "Redundancy", "Encryption at rest"],
    threat: "Physical media compromise",
    threatDetail:
      "A stolen or improperly retired disk yields only encrypted fragments of many different files, each under a different key.",
    fail: "A failed write is retried elsewhere; the commit is not acknowledged until durability is satisfied.",
    chipThreat: "media theft",
  },
  {
    id: "metadata",
    zone: "z-store",
    role: "store",
    icon: "db",
    name: "Metadata store",
    sub: "filename · ACL · pointers",
    what: "Commits the file's metadata — name, owner, permissions, and the map of where its chunks live. This is the record every future access check is decided against.",
    principles: ["Access control", "Integrity", "Consistency"],
    threat: "ACL tampering",
    threatDetail:
      "Permissions are the real gate on every later read, so the metadata record is as security-critical as the bytes themselves — corrupt it and the file is readable by the wrong people.",
    fail: "If the metadata commit fails, the upload is not acknowledged and the orphaned chunks are reclaimed.",
    chipThreat: "ACL tampering",
  },
];

// The thirteen calls, in request order. `kind` drives edge styling.
export const STEPS = [
  {
    source: "client",
    target: "dns",
    kind: "call",
    label: "resolve host",
    title: "DNS resolution",
    sub: "client → DNS / anycast",
    what: "The client resolves the Drive hostname and is routed to the nearest edge. Note what this step does NOT establish: nothing here proves the address it got back is genuinely Google.",
    principles: ["Availability"],
    threat: "DNS spoofing",
    threatDetail:
      "A forged answer sends you to an attacker. The architecture's answer is not to trust DNS at all — the very next step authenticates the server cryptographically.",
    fail: "A hijacked answer survives this step and is caught at TLS instead.",
    state: "still on your disk",
  },
  {
    source: "client",
    target: "gfe",
    kind: "main",
    label: "file bytes",
    lock: "TLS 1.3",
    title: "TLS 1.3 handshake",
    sub: "client → Google Front End",
    what: "The client authenticates the server by certificate and negotiates an encrypted channel, then streams the file. This arrow crosses the first trust boundary: the public internet ends at the GFE.",
    principles: ["Encryption in transit", "Forward secrecy", "Fail secure"],
    threat: "Man-in-the-middle",
    threatDetail:
      "On an untrusted network anyone on the path could read or alter the file. Certificate validation stops impersonation; forward secrecy means a key stolen tomorrow cannot decrypt today's upload.",
    fail: "Certificate mismatch or a downgrade attempt ends the connection before any file data is sent.",
    state: "TLS ciphertext",
  },
  {
    source: "gfe",
    target: "api",
    kind: "main",
    label: "forward request",
    lock: "ALTS",
    title: "Edge to production",
    sub: "GFE → Drive API frontend",
    what: "Having absorbed abuse and terminated TLS, the GFE forwards the request into Google's production network — re-encrypted and mutually authenticated with ALTS, because the internal network is not treated as safe either.",
    principles: ["Defense in depth", "Zero trust", "Rate limiting"],
    threat: "DDoS and implicit network trust",
    threatDetail:
      "Two things happen here: volumetric abuse is filtered before it reaches the application, and the internal hop is authenticated rather than assumed — the perimeter is not the security model.",
    fail: "Traffic scored as abusive is throttled or dropped at the edge and never reaches Drive.",
    state: "ALTS between services",
  },
  {
    source: "api",
    target: "identity",
    kind: "call",
    label: "validate token",
    title: "Authenticate the caller",
    sub: "Drive API → Identity",
    what: "The frontend asks Identity to verify the session or OAuth token on this request. Arriving from inside the network buys the request nothing — it is authenticated on its own merits.",
    principles: ["Zero trust", "Authentication"],
    threat: "Stolen token or replayed session",
    threatDetail:
      "A leaked bearer token impersonates you completely, so lifetimes are short, tokens are bound, and sensitive actions force re-authentication.",
    fail: "Missing, expired, or invalid credential → 401, and the upload stops here.",
    state: "in memory, unstored",
  },
  {
    source: "identity",
    target: "api",
    kind: "ret",
    label: "identity + scopes",
    title: "Authorization decision",
    sub: "Identity → Drive API",
    what: "Identity returns who the caller is and what scopes they hold. Authentication settled identity; this return value is what settles permission — the scope must actually allow creating files, and the target folder's ACL must allow this user to write.",
    principles: ["Least privilege", "Separation of duties"],
    threat: "Over-privileged app / confused deputy",
    threatDetail:
      "A third-party integration with broad access could write anywhere in your Drive. Narrow scopes such as drive.file confine an app to only the files it created itself.",
    fail: "Insufficient scope or no write permission on the destination → 403, and nothing is stored.",
    state: "authorized, unwritten",
  },
  {
    source: "api",
    target: "upload",
    kind: "main",
    label: "open session",
    title: "Resumable upload session",
    sub: "Drive API → Upload service",
    what: "The upload service issues a short-lived, unguessable session URI and accepts the file in chunks, validating size, type, checksum, and quota as they arrive.",
    principles: ["Input validation", "Integrity", "Resource limits"],
    threat: "Malformed input and resource exhaustion",
    threatDetail:
      "Oversized or deliberately malformed uploads are used to exhaust storage or crash whatever parses them downstream. Explicit limits contain both before the file travels further.",
    fail: "403 on quota; a checksum mismatch re-requests the chunk; an expired session URI returns 410.",
    state: "plaintext, staged",
  },
  {
    source: "upload",
    target: "scanner",
    kind: "call",
    label: "scan content",
    title: "Malware scanning",
    sub: "Upload service → scanner",
    what: "Content is scanned against Google's malware signals before the file can be shared or served to anyone.",
    principles: ["Defense in depth", "Containment"],
    threat: "Drive as a malware delivery channel",
    threatDetail:
      "Attackers upload a payload and share the link, borrowing the reputation of a google.com domain to get past filters that would block an unknown host.",
    fail: "Detected malware is blocked from sharing and download, and flagged to the owner and admins.",
    state: "plaintext, under inspection",
  },
  {
    source: "upload",
    target: "dlp",
    kind: "call",
    label: "classify",
    title: "DLP classification",
    sub: "Upload service → DLP engine",
    what: "For organizations, policy inspects the content and applies labels that govern how it may be shared — before it becomes shareable at all.",
    principles: ["Data governance", "Least privilege", "Auditability"],
    threat: "Exfiltration and accidental exposure",
    threatDetail:
      "Sensitive data leaving through a personal account or a public link. Enforced by policy precisely because it is usually carelessness rather than malice.",
    fail: "A violation can block the upload, strip sharing, or quarantine the file, raising an admin alert.",
    state: "classified + labeled",
  },
  {
    source: "upload",
    target: "chunk",
    kind: "main",
    label: "stream chunks",
    lock: "ALTS",
    title: "Into the storage plane",
    sub: "Upload service → chunker",
    what: "The accepted file crosses the last trust boundary into storage, where it is split into chunks and each chunk is encrypted under its own key.",
    principles: ["Encryption at rest", "Blast-radius reduction", "Isolation"],
    threat: "Bulk data compromise",
    threatDetail:
      "One key per chunk, chunks scattered across the fleet: compromising storage yields fragments, not files.",
    fail: "If a chunk fails its integrity check it is never committed.",
    state: "chunked + encrypted",
  },
  {
    source: "chunk",
    target: "keystore",
    kind: "call",
    label: "wrap DEK",
    title: "Key wrapping",
    sub: "chunker → Keystore",
    what: "Each data encryption key is sent to Keystore to be wrapped by a key encryption key, and the wrapped result is stored beside its chunk. Data and the authority to read it live in different systems.",
    principles: ["Key hierarchy", "Separation of duties", "Fail closed"],
    threat: "Key compromise and insider access",
    threatDetail:
      "Because every unwrap is a separate authorization decision that is checked and logged, reaching the storage system is not the same as reaching the content.",
    fail: "If Keystore denies the unwrap, the service cannot read the data — access fails closed.",
    state: "key wrapped separately",
  },
  {
    source: "chunk",
    target: "colossus",
    kind: "main",
    label: "write chunks",
    title: "Durable write",
    sub: "chunker → Colossus",
    what: "Encrypted chunks are written across machines and failure domains with redundancy, and the write is only acknowledged once durability is satisfied.",
    principles: ["Durability", "Redundancy", "Encryption at rest"],
    threat: "Physical media compromise",
    threatDetail:
      "A stolen or improperly retired disk holds encrypted fragments of many different files, each under a different key — physical access alone buys almost nothing.",
    fail: "A failed write is retried on other machines before the upload is acknowledged.",
    state: "encrypted at rest",
  },
  {
    source: "upload",
    target: "metadata",
    kind: "main",
    label: "commit metadata",
    title: "Metadata commit",
    sub: "Upload service → metadata store",
    what: "Name, owner, permissions, and the map of where the chunks live are committed. This record is what every future access check will be decided against.",
    principles: ["Access control", "Integrity", "Consistency"],
    threat: "ACL tampering",
    threatDetail:
      "Permissions are the real gate on every later read, which makes this record as security-critical as the bytes — corrupt it and the right file reaches the wrong people.",
    fail: "If the commit fails the upload is not acknowledged, and the orphaned chunks are reclaimed.",
    state: "stored + permissioned",
  },
  {
    source: "upload",
    target: "audit",
    kind: "call",
    label: "audit event",
    title: "Audit logging",
    sub: "Upload service → audit log",
    what: "The action is recorded — who uploaded what, when, from where. This runs whether the upload succeeded or was refused.",
    principles: ["Auditability", "Non-repudiation", "Detect and respond"],
    threat: "Undetected compromise",
    threatDetail:
      "Every control above can eventually fail. Logging is what makes a breach detectable and reconstructable instead of silent — the design assumption is not if, but when.",
    fail: "Refusals are logged too, so blocked attempts are as visible as successful ones.",
    state: "recorded as an event",
  },
];

export const FOUNDATIONS = [
  {
    name: "Titan & trusted boot",
    text: "Hardware root of trust. Titan chips verify the boot chain, and a machine that fails verification is refused entry to production.",
  },
  {
    name: "ALTS on every hop",
    text: "Each internal service-to-service call is mutually authenticated and encrypted. The internal network is never assumed to be safe.",
  },
  {
    name: "Audit logging",
    text: "Access and admin activity are recorded, so every stage above can be reconstructed after the fact.",
  },
];
